CFLAGS = -m32 -ffreestanding -fno-stack-protector -nostdlib -nostdinc -w -g -I ./ -I 
CFLAGS += -I ./kernel/lib
CFLAGS += -I ./kernel/sys
CFLAGS += -I ./kernel/drivers
CFLAGS += -I ./kernel/mm
CFLAGS += -I ./kernel
CFLAGS += -I ./kernel/fs 
CFLAGS += -I ./kernel/arch
CFLAGS += -I ./kernel/lib/stdlib
CFLAGS += -I ./kernel/cpu/idt -I ./kernel/cpu/gdt
CFLAGS += -I ./kernel/cfgs/
CFLAGS += -I ./boot
